### ISSUE TITLE
Missing library in the Makefile

### ISSUE THREAD

**Issue by raydeejay** [phreda4/r3vm#1]
LIBS should also contain `-lSDL2_net`

**Comment by phreda4** [comment]
thank you!! 
if you like, I can gave access to you, all is open

**Comment by phreda4** [comment]
I remember now, the net lib is a test.. not finish !!

**Comment by raydeejay** [comment]
> I remember now, the net lib is a test.. not finish !!

ok, I won't touch that then... maybe work on it in a different branch? :-)
