### ISSUE TITLE
Segmentation fault after compiling on Manjaro Linux.

### ISSUE THREAD

**Issue by dangerousthing** [phreda4/r3vm#2]
Segmentation fault after building on Manjaro Linux.

**Comment by dangerousthing** [comment]
I compiled this system on Manjaro Linux (gcc 12.1.0), and when I ran it, the following appeared:

r3vm - PHREDA

compile:main.r3... ok.

inc:12 - words:420 - code:15Kb - data:53Kb - free:970Kb

Segmentation fault (core dumped)

Segmentation fault (core dumped)

**Comment by phreda4** [comment]
HI, the interpreter is ready but the link to the OS is not, I only make an example, if you like to try make this

Use the r3 repository 

rename main.r3 to mainw.r3 (is the windows version)
in a new main.r3 text file write

```
^r3/posix/posix.r3
:test  1 "hello " 6 libc-write ;
: test ;
```

if you get hello in the console is all ok..
I need test all the words for call libc in linux and make the link for sdl for work in graphics, etc

**Comment by phreda4** [comment]
![r3lin](https://user-images.githubusercontent.com/425372/181097212-5490c41e-4dab-4331-a146-89dbb5b2bd3d.png)

**Comment by phreda4** [comment]
sorry, for this version you need decomment line 10 ...#define LINUX

**Comment by dangerousthing** [comment]
I have done your changes, but I can't find posix.r3 anywhere in the directory structure. It compiles fine, but gives the following message before it shuts down:

compile:main.r3...FILE r3/poix/posix.r3 not found

**Comment by phreda4** [comment]
sorry, the posix if for new r3evm.. but, if you try this version download de r3d4 repository and try in linux, or copy the r3 folder and main.r3 from the r3d4 distro to here and try again..
